### ISSUE TITLE
loss_G falls first and rises later

### ISSUE THREAD

**Issue by ASLPZHAO** [YBZh/SymNets#2]
Here is the loss_G(from 1st epoch to 19th epoch):
1.36068844
0.94996117
0.85879516
0.86759730
0.89483646
0.92412219
0.95386988
0.98355311
1.01217949
1.04063841
1.06637350
1.09318311
1.11779379
1.14124746
1.16298054
1.18398786
1.20375549
1.22175168
1.23885152

**Comment by yuxiao-ash** [comment]
When I run this code to train the office-31 dataset, the accuracy (top1S and top1T) rises to 100% in epoch 0. Is my dataset path wrong?

**Comment by YBZh** [comment]
> 
> 
> Here is the loss_G(from 1st epoch to 19th epoch):
> 1.36068844
> 0.94996117
> 0.85879516
> 0.86759730
> 0.89483646
> 0.92412219
> 0.95386988
> 0.98355311
> 1.01217949
> 1.04063841
> 1.06637350
> 1.09318311
> 1.11779379
> 1.14124746
> 1.16298054
> 1.18398786
> 1.20375549
> 1.22175168
> 1.23885152

As the training proceeds, the lam gets larger, which may explain the increasing value of Loss_G

**Comment by YBZh** [comment]
> 
> 
> When I run this code to train the office-31 dataset, the accuracy (top1S and top1T) rises to 100% in epoch 0. Is my dataset path wrong?

The expected structure of the dataset is Amazon/category/xxx.jpeg (or .png).

**Comment by heleibin** [comment]
@ASLPZHAO Hi ,Have you met the error in this code:
target_source_temp = target_source + args.num_classes
I am really confused at this! How could these two add together.And what is the purpose of the code above?
Thanks in advance!

**Comment by yuxiao-ash** [comment]
Hi，
the code you mentioned is to get labels for target domain classifier, ie, Ct.
for example, there is a sample from source domain and its label is 5, then the label for Cs is 5 while the label for Ct is 5 plus num_classes.
in addition, a int tensor can add a int number.
hope to help you

---Original---

**Comment by heleibin** [comment]
Oh,I see,thanks.
There are  num_classes*2 labels!

**Comment by heleibin** [comment]
@FishSmile-syx Can you run the code correctly? I met many errors!
`` target_source_temp = target_source + args.num_classes
    target_source_temp = target_source_temp.cuda(async=True)
    target_source_temp_var = torch.autograd.Variable(target_source_temp) #### labels for target classifier

    target_source = target_source.cuda(async=True)
    input_source_var = torch.autograd.Variable(input_source)
    target_source_var = torch.autograd.Variable(target_source) ######## labels for source classifier.

The 'target_source ' is list, and 'args.num_classes' is int .These two cannot add.Then I turn the list into tensor,there has problem too.
And the datatype of target_source_temp  is list,it has no attribute cuda.
Did you change the source code at these places?

**Comment by yuxiao-ash** [comment]
hi,


i have run the symnet's code correctly at May.&nbsp;
&nbsp;i guess the way you use the data is wrong. i remember the label is tensor but not list.&nbsp;
or, i think you can just change the __getitem__ in dataset.
by the way, i didn't need to change the source code. maybe the author changed the code, or maybe you use in a wrong way.
hope to help you



---Original---

**Comment by YBZh** [comment]
> @FishSmile-syx Can you run the code correctly? I met many errors!
> `` target_source_temp = target_source + args.num_classes
> target_source_temp = target_source_temp.cuda(async=True)
> target_source_temp_var = torch.autograd.Variable(target_source_temp) #### labels for target classifier
> 
> ```
> target_source = target_source.cuda(async=True)
> input_source_var = torch.autograd.Variable(input_source)
> target_source_var = torch.autograd.Variable(target_source) ######## labels for source classifier.
> ```
> 
> The 'target_source ' is list, and 'args.num_classes' is int .These two cannot add.Then I turn the list into tensor,there has problem too.
> And the datatype of target_source_temp is list,it has no attribute cuda.
> Did you change the source code at these places?

The ''target_source'' and the "target_source_temp" should be TorchTensor, instead of list.  There should be something wrong with your implementation.  You can provide more code details for a solution.

**Comment by gloomy1999** [comment]
In my opinion, 'loss_category_st_G = 0.5 * criterion(output_source, target_source_var) + 0.5 * criterion(output_source, target_source_temp_var)
' is same as 'loss_category_st_G = 0.5*loss_task_s_Cs+0.5*loss_task_s_Ct'.
Is that right?

**Comment by gloomy1999** [comment]
my bad,there's actually sth different between them,because of the space of Cst
