### ISSUE TITLE
testing classifier

### ISSUE THREAD

**Issue by cuishuhao** [YBZh/SymNets#3]
Thanks for your job.
I get confused in your testing process.
I thought target domain should be tested on Cst, but on Cs and Ct in the code.
Could you please explain why target domain is tested on Cs and Ct?

**Comment by YBZh** [comment]
You may adopt the Cst for testing, I think it is also ok. 
We test the target domain on the Ct since 1. Ct is proposed for the target domain, as we advocate in the paper; 2. the results of Cs and Ct are almost consistent.
